### ISSUE TITLE
Feature request: Support method chaining

### ISSUE THREAD

**Issue by taleinat** [Suor/funcy#101]
I would find method chaining very useful. This style is made available in many similar libraries, e.g. [underscore](http://underscorejs.org/#chain), [lodash](https://lodash.com/docs/4.17.15#chain), [pydash](https://pydash.readthedocs.io/en/v5.0.2/chaining.html) and pandas.

This is the only feature I've really been missing in funcy.

**Comment by Suor** [comment]
This is out of funcys scope, may be implemented in a separate library.

**Comment by Suor** [comment]
Somewhat related https://github.com/Suor/funcy/issues/48.

**Comment by taleinat** [comment]
Thanks for the response, @Suor.

Are you aware of existing libraries which provide such functionality and interoperate nicely with funcy?

**Comment by Suor** [comment]
I'm not.

**Comment by taleinat** [comment]
See [funcy-chain](https://github.com/taleinat/funcy-chain). Feedback would be very welcome!

**Comment by Suor** [comment]
Thanks, I see a couple of issues though:
- `chain()` is kind of used already by `itertools.chain()`. Simply capitalizing might fix it, i.e. `Chain()`.
- you don't preserve any laziness, which make a sense for nested calls like these.

**Comment by taleinat** [comment]
Thanks for taking a look @Suor!

> chain() is kind of used already by itertools.chain(). Simply capitalizing might fix it, i.e. Chain().

Very good point, I hadn't considered that. Hmm...

> you don't preserve any laziness, which make a sense for nested calls like these.

That's intentional, to keep things simple and easy to debug. I was thinking of having a parallel lazy version ("ichain"?) that would use lazy/iterator-style operations where possible. That way the style used would be very explicit, and one temporarily swap "ichain" for "chain" to be able to debug step-by-step. WDYT?

**Comment by Suor** [comment]
Another thing that I would add is pure chains, i.e. ones not bound to data, callable instead. Will make chains reusable and pluggable:

```python
get_total = C.keep(itemgetter("amount")).sum()
amount_by_color = Chain(seq)
    .group_by(itemgetter("color")).walk_values(get_total)

# or for reuse
get_amount_by_color = C
    .group_by(itemgetter("color"))
    .walk_values(C.keep(itemgetter("amount")).sum())
```

List vs iterator stuff might be more usefully resolved at higher level than individual method I guess:
```python
Chain(...).filter().map()      # makes lists at all stages
LazyChain(...).filter().map()  # makes iters at all stages
```

**Comment by Suor** [comment]
**P.S.** Here is an example of this approach with utilities specific to parsing https://github.com/Suor/parsechain

**Comment by taleinat** [comment]
> Another thing that I would add is pure chains, i.e. ones not bound to data, callable instead. Will make chains reusable and pluggable:

I've seen that in pydash, but I'm not sure what the benefit is vs. just using a lambda or function:

```python3
def get_total(flower_datum):
    return Chain(flower_datum).keep(itemgetter("amount")).sum()
amount_by_color = Chain(seq).group_by(itemgetter("color")).walk_values(get_total)

get_amount_by_color = (
    chain(data)
    .group_by(itemgetter("color"))
    .walk_values(lambda value: Chain(value).keep(itemgetter("amount")).sum())
).value
```

> List vs iterator stuff might be more usefully resolved at higher level than individual method I guess:

Indeed, that's what I have in mind.

**Comment by Suor** [comment]
```python
lambda value: Chain(value).keep(itemgetter("amount")).sum()
# vs
C.keep(itemgetter("amount")).sum()
```

One might ask why you need `Chain(...)` :)

**Comment by taleinat** [comment]
> ```python3
> lambda value: Chain(value).keep(itemgetter("amount")).sum()
> # vs
> C.keep(itemgetter("amount")).sum()
> ```

Since both options would be spelled with similar length, and because funcy-chain supports funcy-style function-making, a fairer comparison would be:

```python3
lambda value: C(value).keep("amount").sum()
# vs.
C.keep("amount").sum()
```

Yes, the second option is shorter, but requires learning/remembering more, and creates overall higher cognitive load IMO.

> One might ask why you need Chain(...) :)

Yes! Code-aestheitic libraries such as this tend to be a slippery slope! That's precisely why I wrote funcy-chain: I like funcy while I avoid pydash and fluentpy; the latter pair are far too clever and provide too many ways of doing things. funcy-chain provides *exactly one* new style of writing sequences of manipulations on some data, and it does so in a way that is as clear and simple as possible, with no extra features.

**Comment by taleinat** [comment]
FYI, I've added `IterChain`.

**Comment by vovavili** [comment]
> So I wrote one. See [funcy-chain](https://github.com/taleinat/funcy-chain). Feedback would be very welcome!

That's actually a pretty clever way of doing things, coming from a person who is a heavy user of pandas.
