### ISSUE TITLE
Apply a list object to a function's argument-list  

### ISSUE THREAD

**Issue by amitSA** [Suor/funcy#112]
I'm asking for a `funcy.apply` function that given a `fn` and `list` it would do `fn(*list)`  .  This would be helpful in pipelines

See this example

```
from funcy import rcompose, partial, concat

from funcy import apply # new function

rcompose(
  # state: [ [1], [2] ]
  partial(apply,concat)
  # state: [1,2]
)()
```

The workaround which I find more ugglier is: 
```
rcompose(
  # state: [ [1], [2] ]
  lambda x: concat(*x)
  # state: [1,2]
)()
```

Do people agree with my request for `funcy.apply` ?

**Comment by Suor** [comment]
So `partial(apply, concat)` vs `lambda x: concat(*x)`:
- components 3 vs 4. `lambda`, `x` `concat` and unpacking on right side
- non builtin things 3 vs 1
- non stdlib things 2 vs 1

I don't see much gain in `apply()` here. Considering a cost of introducing a new thing looks like net negative gain.

Also can simply use `cat` for this particular case.

**Comment by amitSA** [comment]
My actual use case was for `funcy.merge` instead of `funcy.cat` 

But you make a fair argument, will close the ticket.
