### ISSUE TITLE
funcy.autocurry doesn't work with functions with key-words only 

### ISSUE THREAD

**Issue by ADR-007** [Suor/funcy#115]
Hi! I'm happy to use the library but looks like I found a bug:
```
>>>@funcy.autocurry
...def a(b, c): return b + c

>>>a(c=1)(2)
3

>>>@funcy.autocurry
...def aa(b, *, c): return b + c

>>>aa(c=1)
Traceback (most recent call last):
   ...
TypeError: aa() missing 1 required keyword-only argument: 'c'
```

funcy version: 1.17

**Comment by Suor** [comment]
Can you write a test?

пн, 7 мар. 2022 г., 02:11 Adrian Dankiv ***@***.***>:

**Comment by Suor** [comment]
There are several points in funcy where it fails with kwonly args. Looks like fixing it is complicated by Python 2 support. I will consider dropping it and then fixing this stuff.

**Comment by Suor** [comment]
So, dropped Python 2 recently. Improved positional only and kw only args support in @decorator.

**Comment by Suor** [comment]
Fixed in https://github.com/Suor/funcy/commit/5dc4547e05b00a85f44635f585cc69135a30babc.
