### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by bersbersbers** [Suor/funcy#125]
I am using (a subset of) funcy functionality successfully on Python 3.11, but I was surprised to see that 3.11 is not listed here 

https://github.com/Suor/funcy/blob/416c187374a86b27ebd7ea882bb38764390e46ae/setup.py#L34-L37

nor here

https://github.com/Suor/funcy/blob/416c187374a86b27ebd7ea882bb38764390e46ae/tox.ini#L2

nor here

https://github.com/Suor/funcy/blob/416c187374a86b27ebd7ea882bb38764390e46ae/.github/workflows/test.yml#L43

Would it be a lot of work to support it?

**Comment by Suor** [comment]
Python 3.11 worked from the start. The issue was with a tests dependency `whatever` lib. I've updated that to support Python 3.11 now and added testing against Python 3.11 here too.
