### ISSUE TITLE
Flow function `retry` as non-decorator variant

### ISSUE THREAD

**Issue by amotl** [Suor/funcy#126]
Dear Alexander,

thanks a stack for conceiving and maintaining this excellent library. We've only recently started to use it within [mqttwarn](https://mqttwarn.readthedocs.io/), and it is a pleasure to work with.

With https://github.com/jpmens/mqttwarn/pull/639, we are adding a [`load_file(path, retry_tries=None, retry_interval=0.075)`](https://github.com/jpmens/mqttwarn/blob/5b72f21fb9c3b4587aa105b5884b94b090744d66/mqttwarn/util.py#L234-L249) function, which needed to use [`funcy.retry()`](https://funcy.readthedocs.io/en/stable/flow.html#retry) in an imperative way, instead of using it as a decorator, because we needed to make it obtain its arguments `tries` and `timeout` at runtime.

It took a while to figure out the right incantation, but we finally discovered a corresponding call within funcy's software tests.
```python
call = functools.partial(open, path, "rb")
funcy.retry(tries=int(retry_tries), timeout=float(retry_interval))(call)()
```

While it works excellently for us - thanks again! - would you consider providing a non-decorator variant of that or other (flow) functions, in order to make them easier to use in scenarios like ours? Otherwise, it may make sense to improve the documentation correspondingly, if you also would like to demonstrate those kinds of alternative use cases?

With kind regards,
Andreas.

**Comment by Suor** [comment]
Given that decorator syntax is just a sugar one might go pre Python 2.4 way:

```python
decorated = decorator(...)(func)
```

A more specific example can be found in [this post](https://suor.github.io/blog/2013/10/08/abstracting-control-flow/) (search for "retry"). Or in you case:

```python
def load_file(path: str, retry_tries=None, retry_interval=0.075, unlink=False) -> t.IO[bytes]:
    """..."""
    if unlink:
        try:
            os.unlink(path)
        except:
            pass

    _open = open
    if retry_tries:
        logger.info(f"Retry loading file {path} for {retry_tries} times")
        _open = funcy.retry(tries=int(retry_tries), timeout=float(retry_interval))(open)
    return _open(path, "rb")
```

Not sure what non-decorator variant would help here, if it is something like:

```python
_open = funcy.retry(open, tries=int(retry_tries), timeout=float(retry_interval))
```

Then it doesn't fill worth it for me. Actually being even a bit hurtful by providing an extra way to do the same with a non-significant consiseness gain. If you mean some sort of composition with `partial` for each of funcy's decorator then it also doesn't feel worth it - I would prefer things stay decomposed. 

To the last on there is [a tangentially related issue](https://github.com/Suor/funcy/issues/48), the justification is the same here.

**Comment by amotl** [comment]
Dear Alexander,

thank you for sharing your excellent article [Abstracting Control Flow](https://suor.github.io/blog/2013/10/08/abstracting-control-flow/).

> Not sure what non-decorator variant would help here [...]. It doesn't fill worth it for me. Actually being even a bit hurtful by providing an extra way to do the same with a non-significant consiseness gain. If you mean some sort of composition with partial for each of funcy's decorator then it also doesn't feel worth it - I would prefer things stay decomposed.

I can completely follow your point here. Thanks a stack for your swift response.

Also, thank you very much for providing a more readable/structured variant of our `load_file()` function. I love it!

With kind regards,
Andreas.
