### ISSUE TITLE
Adding a `flip` function to funcy

### ISSUE THREAD

**Issue by piotrklibert** [Suor/funcy#24]
Hi,

every time I try to code in a more functional manner in Python I find myself writing this little function sooner or later:

```python

flip = lambda f: lambda x,y: f(y,x)
```

it's especially useful with currying, which is already provided by the library, so I think it would be a good addition. A very simple example:

```python

has_suffix = curry(flip(str.endswith))
filter(has_suffix("a"), ["ab", "ba", "cd"])
```

One thing to think about is the semantics of `flip` when used on a function with more than two arguments and on functions with `**kwargs`, especially the former case is interesting, as it could mean:

```python

flip = lambda f: lambda a,b,*args: f(b,a,*args)
```

or

```python

flip = lambda f: lambda *args: f(*(args[1:] + [args[0]]))
```

The latter meaning would be consistent with for example `rotatef` from CL, but on the other hand it could be less practical.

**Comment by Suor** [comment]
Also, you can use [whatever](https://github.com/Suor/whatever) library for your example:
```python
from whatever import _
one_third = _ / 3
```

**Comment by Suor** [comment]
Or even this way:
``` python
one_third = (3).__rdiv__
```

**Comment by Suor** [comment]
I added `back_partial()` and `backcurry()` functions to help with your use cases:
```python
has_suffix = backcurry(str.endswith)
one_third = back_partial(div, 3)
```

Not sure with naming, looks inconsistent, but it I already have `func_partial()` and `autocurry()`. Do you have better ideas?

Regarding `flip()`. This name is already used to flip dicts, so not sure how to handle that. I will probably just leave it out, since new functions cover it some way.

**Comment by piotrklibert** [comment]
> I added back_partial() and backcurry() functions to help with your use cases

Yes, that will do. I recently did a talk on FP in JavaScript and surveyed quite a lot of FP libraries (see [here](https://klibert.pl/warsawjs-talk/?full#8) if you want) and most of them had functions to this effect.

http://ramdajs.com/docs/#rPartial
https://lodash.com/docs#curryRight
https://lodash.com/docs#partialRight
https://github.com/raganwald/allong.es#variations-on-the-order-of-applying-the-arguments
http://eliperelman.com/fn.js/#curryRight

`flip` is provided only here:

http://bilby.brianmckenna.org/#flipf
http://www.preludels.com/#flip

but at least in case of Prelude.ls there's no need for `rPartial` because LiveScript provides dedicated syntax for partial application (see second example [here](https://klibert.pl/warsawjs-talk/code.html#text-3-3)). Anyway, this seems to suggest that providing right-to-left version of curry and partial is the more general and more expected approach.

About the names you choose, as you can see from the examples most libraries use "r" as a prefix for those functions, but I think "back" makes perfect sense too. One thing that does puzzle me is why there's no underscode in `backcurry`? I think it would be better to make the naming consistent and have either `back_curry` and `back_partial` or `backcurry` and `backpartial`.

(BTW: yes, I noticed that `flip` name is already taken but only after I posted this issue, sorry about that.)

Sorry for taking this long to respond and thanks for including these (and for funcy in general, too)!

**Comment by Suor** [comment]
`backcurry()` is consistent with `autocurry()`. The reason is "back" modifies a verb as in "backstab", but it works as a separate word with nouns. E.g. `auto_curry()` looks weird, but `autocurry()` makes sense. Do you think I fell english wrong here?

**Comment by Suor** [comment]
I added `flip()` in "do what I mean" style - https://github.com/Suor/funcy/commit/8b0b3f690f94372cb58a5235a176bbda0383cfc2 and I am not happy with how it complicated things: implementation, tests, docs.

**Comment by Suor** [comment]
Renamed `back_partial()` to `rpartial()` and `backcurry()` to `rcurry()` in 4b0bcd6448c35c794e22c8adc2310b92a962c94d.

**Comment by Suor** [comment]
Reverted adding `flip()` in 9d5e81eb2e3c1f908ee56b849505d69f6d82cb3f.

Let's see if `rpartial()` and `rcurry()` is enough. If you have good usage examples for any of these you are welcome.
