### ISSUE TITLE
documenting issues with @cached_property

### ISSUE THREAD

**Issue by bastianh** [Suor/funcy#25]
Hi,

when I use @cached_property on a class function it won't get documented by sphinx autodoc.

Is there a way to fix that or a workaround ?

Thanks,
bastian

found following notice in the spinx docs:

If you document decorated functions or methods, keep in mind that autodoc retrieves its docstrings by importing the module and inspecting the __doc__ attribute of the given function or method. That means that if a decorator replaces the decorated function with another, it must copy the original __doc__ to the new function.
From Python 2.5, functools.wraps() can be used to create well-behaved decorating functions.

**Comment by Suor** [comment]
Thanks for pointing this out.

**Comment by bastianh** [comment]
Thanks for fixing... you have a great library ;)
