### ISSUE TITLE
How to run the tests

### ISSUE THREAD

**Issue by paulmelnikow** [Suor/funcy#32]
Hi there, neat library!

Can you provide some documentation about how to run the tests?

I installed tox and ran it, and seem to have encountered some setuptools-related errors, and am wondering if there are some other steps I should take. I'm on Mac OS if that's helpful.

**Comment by Suor** [comment]
You should be able to do:
```
pip install -r test_requirements.txt
py.test
```

To fully run `tox` you need all the supported pythons to be installed. These are 2.6, 2.7, 3.3, 3.4, PyPy and PyPy3.

**Comment by Suor** [comment]
**P.S.** If you are developing something it's ok to only test with Python 2.7 or whatever you have (and Python 3 if you in doubt) and then let Travis test the rest.

**Comment by paulmelnikow** [comment]
Thanks. I'll open a PR with that info.
