### ISSUE TITLE
String replacement

### ISSUE THREAD

**Issue by vm** [Suor/funcy#36]
Hello,

Is there something in this library to do this:
```.py
'my name is vignesh'.replace('vignesh', 'matt').replace('my', 'your')
```

I've written for loops, regex and reduces to implement this, but its very repetitive to rewrite each time. What do you recommend?

Issues with for loops and reduces include:
- Reduces are not recommended by Guido.
- The ordering matters, since they are not replaced at once.

Regex works, but its not very functional. Although I guess it doesn't matter if the implementation itself is function, just whether the API is in this case, right?

**Comment by Suor** [comment]
Won't str.format work for you? If not just make a function and use it.
Funcy doesn't have special purpose function for it.
