### ISSUE TITLE
Allow item lists in `join_with`?

### ISSUE THREAD

**Issue by vspinu** [Suor/funcy#40]
Thanks for the great package!

I am looking for a way to do `join_with` on binary tuples. Something like 

```python
join_with(list, [{1:2}, {1: 3}])
## {1: [2, 3]}
```

But with tuples:
```
join_with(list, [(1,2), (1, 3)])
## {1: [2, 3]}
```

What would be an idiomatic way to achieve this with `funcy`? 

Thanks.

**Comment by Suor** [comment]
The most sane thing is just using `defaultdict()`. The task is so common though that I added it to funcy few months ago, just not released it yet:
```python
def group_values(seq):
    result = defaultdict(list)
    for key, value in seq:
        result[key].append(value)
    return result
```

**Comment by vspinu** [comment]
Cool. But it's less general than `join_with` as it doesn't accept a joining function. 

When is the new release expected?

**Comment by vspinu** [comment]
BTW, how does `group_values` fit into overall naming conventions?  While it has `group` as in `group_by` it also has `_values` as in `select_values`. I find a bit confusing because `select_values` is a transformation function. 

Wouldn't `group_by_key` be a better name for this?

Also, extended function semantics seem to imply that `group_by(0, [(1,2) (1, 3)])` should do the trick. But it doesn't work. 

```
>>> group_by(0, [(1,2) (1, 3)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'tuple' object is not callable
>>> 
````

**Comment by vspinu** [comment]
Corrections:

> Wouldn't group_by_key be a better name for this?

I meant `group_values_by_key`. There is already `group_by_keys` functions. 

> But it doesn't work. 

It actually works, but it doesn't give the desired result:

```
>>> group_by(0, [(1,2), (1, 3)])
defaultdict(<type 'list'>, {1: [(1, 2), (1, 3)]})
>>> 
````

**Comment by Suor** [comment]
`walk_*()` and `select_*()` are for collections, `group_by()` and friends are for sequences. We are grouping by key by default, no point in mentioning it. We group items by default, but in your example you want to group values in `(key, value)` pairs, hence `group_values()`.

`group_by()` could be used like:
```python
>>> from funcy import walk_values, partial, map, group_by
>>> walk_values(partial(map, 1), group_by(0, [(1,2), (1, 3)]))
defaultdict(<function <lambda> at 0x7fe8206db140>, {1: [2, 3]})
```

But this is both ugly and inefficient.

**Comment by vspinu** [comment]
> want to group values in (key, value) pairs, hence group_values().

Yes I see that. I guess the general mnemonic rule is to focus on the action verb -  `group`, `walk`, `select` rather on the object that follows.

> But this is both ugly and inefficient.

How about my point on `group_value_by` and `group_values_by_keys`? Could they be implemented efficiently?

One can do `group_values_by(0, seq)` instead of `group_values(seq)`. I think that slightly more typing is a small price to pay fro the generality of it. They are also better and more consistent mnemonics IMHO.
