### ISSUE TITLE
`join_with` fails with `concat`

### ISSUE THREAD

**Issue by vspinu** [Suor/funcy#41]
```
>>> join_with(concat, [{1: [1,2]}, {1: [2,3]}])
{1: [[1, 2], [2, 3]]}
````

I was expecting 

```
{1: [1, 2, 2, 3]}
```

**Comment by Suor** [comment]
`join_with()` is designed to work with aggregating functions, i.e. taking single sequence argument. `concat()` expects many arguments. In your case one should use `cat()`:
```python
>>> join_with(cat, [{1: [1,2]}, {1: [2,3]}])
{1: [1, 2, 2, 3]}
```

**Comment by vspinu** [comment]
Thanks!
