### ISSUE TITLE
Intermittent test failures

### ISSUE THREAD

**Issue by medecau** [Suor/funcy#44]
When running tests in a computer under load the following test fails intermittently.

https://github.com/Suor/funcy/blob/00863de7a8c5be2ac6503493e01f0b0281bab128/tests/test_flow.py#L72

This problem was exposed when I ran the tests using `detox`. I've seen failures on both the static and exponential timeouts.

**Comment by Suor** [comment]
This test is expected to fail under load. I can't see how you can fix that
without losing some test functionality.

**Comment by medecau** [comment]
What is the purpose of the test? Are we testing that the elapsed time is within an expected interval? Essentially testing `time.sleep()`. If that is the case then drop the test altogether. Otherwise it might be better to rethink the test.

**Comment by Suor** [comment]
Testing that sleeps are executed only when needed and in the right amount.

Why are you testing funcy anyway?

**Comment by medecau** [comment]
I ran the tests to make sure they were passing.

**Comment by Suor** [comment]
My resume. These are possible fixes:

1. Drop test.
2. Patch `time.sleep()`.

However, still this is not really an issue I'll do nothing now. I will return to it if someone developing funcy will get that.
