### ISSUE TITLE
get_in should not recurse into strings

### ISSUE THREAD

**Issue by matthewwillian** [Suor/funcy#45]
```
In [6]: d = {'a': {'b': 'carrot'}}
In [7]: funcy.get_in(d, ['a', 'b', 'c'])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-290dd7587deb> in <module>()
----> 1 funcy.get_in(d, ['a', 'b', 'c'])
/Users/matthewwillian/zentreefish/.inenv/zentreefish/lib/python2.7/site-packages/funcy/colls.pyc in get_in(coll, path, default)
    226     for key in path:
    227         if key in coll:
--> 228             coll = coll[key]
    229         else:
    230             return default
TypeError: string indices must be integers, not str
```
I think the correct behavior here should be to return None (or whatever default is set to). The obvious way to fix this would be to return default if coll is a string. Is that the preferred solution?

**Comment by Suor** [comment]
First, now it works with strings with integer indexes, so this will be backward incompatible change. So I need a very good reason to change this behavior.

Second, distinguishing between types as opposed to supported protocols seems unpythonic to me.

**Comment by matthewwillian** [comment]
how does it work for strings with integer indexes?
```
In [8]: d = {'a': 'foo'}

In [9]: funcy.get_in(d, ['a', 1])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-bb7ad592a44c> in <module>()
----> 1 funcy.get_in(d, ['a', 1])

/Users/matthewwillian/zentreefish/.inenv/zentreefish/lib/python2.7/site-packages/funcy/colls.pyc in get_in(coll, path, default)
    225 def get_in(coll, path, default=None):
    226     for key in path:
--> 227         if key in coll:
    228             coll = coll[key]
    229         else:

TypeError: 'in <string>' requires string as left operand, not int
```

**Comment by matthewwillian** [comment]
regardless, looking over the code at HEAD, you seem to have fixed the issue by swallowing the IndexError and KeyError

**Comment by Suor** [comment]
HEAD is the same as 1.7.1 and support for sequences was added even earlier by avoiding using `in`. Exceptions are not swallowed but handled according to `get_in()` semantics.

Overall, current approach looks solid. We could discuss use cases though. What are yours?
