### ISSUE TITLE
All functions in the library should be curried.

### ISSUE THREAD

**Issue by ghost** [Suor/funcy#48]
I think making all functions from `funcy` automatically curried would simplify a vast number of use cases. For example, for an `extract_int` example (where `extract_int("Hello, 123! We are 456!")` => `[123, 456]`), without autocurry, the current best way to do this is:

```python
from funcy import map, partial, rcompose, re_all
extract_int = rcompose(partial(re_all, r'\d+'), partial(map, int))
```

Of course, we could use `autocurry` on them ourselves - but this doesn't seem to work well with some functions (I tested only with `map` and `re_all`, surprisingly `re_all` works):

```python
>>> from funcy import map, autocurry
>>> map = autocurry(map)
>>> map(int)([1, 2, 3])
# .... blah error stuff ....
TypeError: map() requires at least two args
```

This and other such problems could be averted by having all functions (at least those in the library) automatically curried.

**Comment by eshansingh** [comment]
Though note that I have reason to believe the `map` error might be just a naming conflict; it's a completely separate issue anyway.

**Comment by Suor** [comment]
Or you can just write:
```python
def extract_ints(s):
    return map(int, re_iter('\d+', s))
```
Which would be no less readable and probably more efficient. I want to say that curried use is not that needed and in my opinion doesn't justify complicating everything by autocurrying.

I would probably consider separate namespace for autocurried functions. So that you can do:
```python
from funcy.curried import map, re_iter, rcompose

extract_int = rcompose(re_iter('\d+'), map(int))
```
But I am still not convinced of its wide usability. Need more usage examples or more people wanting this, preferable both.

**Comment by Suor** [comment]
**P.S.** The thing with `map()` is it has variable args, so you need specify limit to `autocurry()`:
```python
map = autocurry(map, 2)
```

**Comment by eshansingh** [comment]
As there is clearly no interest here, I'll close this issue in the interests of keeping the backlog up-to-date.

**Comment by Suor** [comment]
Everyone welcome to add their use cases or even just thumb up original post.

**Comment by wooandoo** [comment]
Hello,

I use JS and Python in my projects, and I write my JS code with Ramda, a functional library which has all its functions curried. It's very powerful to build new functions by composing others.

See at http://fr.umio.us/favoring-curry/ "So How Important Is The Currying?"
or https://hughfdjackson.com/javascript/why-curry-helps/

And the curry function in funcy would be smarter without the argument "n", like for toolz:
https://github.com/pytoolz/toolz/blob/master/toolz/functoolz.py

**Comment by Suor** [comment]
Updated `@autocurry` to be much smarter, i.e. handle builtins and classes. Will, also, handle ambiguous  functions like `map()` and `iter()`.

`func.curried` namespace is on the table, all functions curried is not.

**Comment by Netherdrake** [comment]
> funcy.curried namespace is on the table, all functions curried is not.

What would be the downsides of autocurrying funcy methods by default?

**Comment by Suor** [comment]
Besides variable arguments are optional arguments, including first ones and delaying of `TypeError`s, which will be confusing and not backwards compatible.

I don't see `mapc()` and `filterc()` as valuable additions as you can easily write:
```python
mapc, filterc = autocurry(map), autocurry(filter)
```

At some point I was thinking adding `.p` to partially apply all funcy functions:
```python
extract_int = rcompose(re_all.p(r'\d+'), map.p(int))
```
This won't add new imports and more predictable/controllable then autocurrying. But I am still not sure.

**Comment by Suor** [comment]
Thinking a bit more about this I would rather implement it like:
```python
from funcy import partial
extract_int = rcompose(partial.re_all(r'\d+'), partial.map(int))
```
Possibly to be used like:
```python
from funcy import partial as p
extract_int = rcompose(p.re_all(r'\d+'), p.map(int))
```
It could be more clearly implemented as some of funcy functions are reexports, e.g. `icat = chain.from_iterable`.

BTW, the reason I use partial instead of autocurrying is that it's much simpler and more predictable: never fires on first call, always fires on second one. Implementation is also simpler and faster. And this is all you really need to compose chains people want to construct.

**Comment by Netherdrake** [comment]
Quite clever and clean. 

Similar to: `from toolz import curried as c`

**Comment by Suor** [comment]
From other hand:
```python
extract_int = rcompose(p(re_all, r'\d+'), p(map, int))
```
is same number of symbols and parentheses, does not require new abstraction and works for any function. So, I am not convinced.

Maybe this should be solved outside funcy, by some other means. What's the best way to chain functions?

**Comment by Suor** [comment]
Possible syntax is:
```python
extract_int = F.re_all(r'\d+').map(int)
```

**Comment by Suor** [comment]
Closing this is out of scope.
