### ISSUE TITLE
Deprecation Warning - inspect.getargspec()

### ISSUE THREAD

**Issue by dhiana** [Suor/funcy#49]
Hey there,

This library is a dependency for PyLDAVis and I'm having this issue running on Python 3.5.1

funcy/decorators.py:56: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead

https://github.com/Suor/funcy/blob/master/funcy/decorators.py#L56

It is also being used in other parts of the code in the repo.

**Comment by Suor** [comment]
Fixed in bf453740e3f13944c176938b236cd977eb89e298

**Comment by dhiana** [comment]
Thanks, @Suor! 👍 

Can you make it available as a release so that pip installation gets this change?
