### ISSUE TITLE
clear memoize for unit tests?

### ISSUE THREAD

**Issue by rhan-mentad** [Suor/funcy#51]
Is there a recommended way to clear funcy's memoize cache for unit tests without needing to use child processes?

**Comment by rhan-mentad** [comment]
Nevermind, I can just put it in a helper function without `@memoize`

**Comment by Suor** [comment]
Or you can access wrapped function via `.__wrapped__`:

```python
@memoize
def some_func(arg):
    # ...

not_memoized_some_func  = some_func.__wrapped__
```

All decorators in funcy supply that, and all decorators using `@wraps` or `@decorator`.
