### ISSUE TITLE
Play nicely with static code analyzers

### ISSUE THREAD

**Issue by taleinat** [Suor/funcy#53]
In my case, PyCharm has trouble understanding things coming from `funcy`. Specifically, it fails to understand importing directly from the `funcy` package rather than the specific sub-modules, i.e. `from funcy import merge` causes it to mark the import as problematic. I imagine it has other issues too, I haven't investigated further (yet).

I can think of several ways to improve the situation:

1. Re-work the fancy importing mechanisms so that static analyzers do a better job of understanding them.
2. Include stubs which will directly inform static analyzers about the structure of the `funcy` library and its contents
3. Contribute stubs for `funcy` to [the typeshed project](
https://github.com/python/typeshed/), which is used by various static analyzers and IDEs.

I'd be happy to help with this, if the maintainer(s) are open to it.

**Comment by Suor** [comment]
The core issue is that funcy uses different interface in Python 2 and 3. The switch is [made dynamically](https://github.com/Suor/funcy/blob/1.8/funcy/__init__.py) like:
```python
if PY2:
    from .py2 import *  # noqa
    from .py2 import __all__
else:
    from .py3 import *  # noqa
    from .py3 import __all__  # noqa
```
And when `py2` and `py3` have renaming magic in them. Not sure how this could be fixed. Anyway if there is a way I am open to it.

**Comment by taleinat** [comment]
That's why I mentioned options #2 and #3: supply stubs as part of the package, or have stubs in `typeshed`.

For the PyCharm case, it seems #2 is preferable. See: https://www.jetbrains.com/help/pycharm/type-hinting-in-pycharm.html

It would likely be possible to generate such stubs automatically, but I couldn't find tools for that with a quick search.

**Comment by Suor** [comment]
This 91ad761a6656c6fea4266db477a5e607eeb31237 should help. Try it and close if works.

**Comment by taleinat** [comment]
Works great!

Now I'll just wait for the next release so I can update our `requirements.txt`.

**Comment by Suor** [comment]
Ok, great. Note that this don't actually do any type hinting, just fixes imports. For now I see type hinting as low value for funcy since most things are too generic.

**Comment by taleinat** [comment]
I understand, type hinting wasn't the priority for me either.

Regarding things being generic, I still think type hinting would be useful for most functions. That would especially be true if some kind of explicit type-specific dispatch were used, e.g. `singledispatch`.

**Comment by vlasovskikh** [comment]
Due to [this bug](https://youtrack.jetbrains.com/issue/PY-25695) PyCharm fails to statically analyse `__all__` in this case, although it can understand simpler cases of `+=`, `.append()` and `.extend()` on `__all__`.

**Comment by taleinat** [comment]
Thanks for the heads up, @vlasovskikh! I'm glad this is being taken care of at the origin of the issue.

**Comment by uhbif19** [comment]
@taleinat As far, as I understand the typing problems is out of scope of this issue? 

While importing might get working, i see no types annotations, so mypy wont work. Do I understand correctly? May I open separate issue for this?

**Comment by Suor** [comment]
There is no plans to add type annotations to funcy.

**Comment by uhbif19** [comment]
@Suor Do you think this feature does not match with design or goals of the project? Or it is just matter of contribution? I could try work in this direction in that case. I think that even partial type annotation (not sure if for complex decorators annotation without mypy plugin is possible) would be  valuable for teams using funcy with strict mypy linting.

**Comment by Suor** [comment]
@uhbif19 I see no value here.

**Comment by aronszanto** [comment]
Hi @Suor - we absolutely love funcy and use it often. We also gain a tremendous amount of value out of using mypy. We find that adding type annotations to a project increases the trust in its correctness and the ease with which it can be taken up in a typehinted codebase. We'd also be very happy to contribute.

Could you say a little bit more about your reservations? Thank you very much again for this wonderful addition to the open source space!

**Comment by Suor** [comment]
funcy is flexible and types are the opposite of that. So not considering adding types to funcy.
