### ISSUE TITLE
`where` crashes if one of the mappings doesn't have one of the keys in it

### ISSUE THREAD

**Issue by despawnerer** [Suor/funcy#54]
This code:
```python
mappings = [{ 'a': 4 }, { 'b': 2 }]
print(list(where(mappings, b=2)))
```

Raises this exception currently:
```python
KeyError: 'b'
```

Is this intended behavior? It feels like, logically, it should just skip over items that don't have necessary keys in them as they, by definition, don't match the conditions.

**Comment by Suor** [comment]
In funcy I lean towards DWIM (Do what I mean) attitude, so +1 to this. Added a comment to your PR.

As a side note you can use `lwhere()` in python 3 instead of `list(where(...))`.
