### ISSUE TITLE
make_lookuper is misspelt; should be make_lookupper

### ISSUE THREAD

**Issue by eykd** [Suor/funcy#56]
[Two P's.](http://funcy.readthedocs.io/en/stable/calc.html#make_lookuper) :) Perhaps an alias could be made for the misspelt version, for a deprecation period?

**Comment by eykd** [comment]
Oh, same case for [`silent_lookuper`](http://funcy.readthedocs.io/en/stable/calc.html#silent_lookuper).

**Comment by Suor** [comment]
Not sure:

1. There is no such word and double letter rule is not without exceptions.
2. Google suggests "maybe you looked for lookuper" when searching lookupper.
3. lookupper looks like "look upper", which is totally out.

**Comment by Suor** [comment]
Closing it for now.
