### ISSUE TITLE
Add function(s) for keeping unique items in collections

### ISSUE THREAD

**Issue by taleinat** [Suor/funcy#65]
I propose that something like [Lodash's `_.uniq`](https://lodash.com/docs/4.17.5#uniq) could be useful, especially with an optional "key" function similar to [Lodash's `_.uniqBy`](https://lodash.com/docs/4.17.5#uniqBy).

Simply using `list(set(collection))` doesn't preserve the original order.

**Comment by Suor** [comment]
What about distinct()?

**Comment by taleinat** [comment]
I missed `distinct()` despite using funcy a lot lately and searching it for something like this!

I suggest mentioning the word "unique" in the related docs, then, to make it more discoverable.

**Comment by Suor** [comment]
Yes, there are just too many of them). BTW, do you use funcy [cheatsheat](http://funcy.readthedocs.io/en/stable/cheatsheet.html)? The idea for this particular case - you need do something with sequence, remove some elements from it so you go to `Sequences -> Filter` and find `distinct()` there.

**Comment by taleinat** [comment]
That cheatsheet is awesome!

Would you be open to a doc PR adding "unique" to the description somewhere?

**Comment by Suor** [comment]
How you want to describe it then? I prefer docs to be succinct. I see how people would google "unique" though.

**Comment by taleinat** [comment]
Maybe something like:
"Iterates over sequence skipping duplicates" -> "Iterate over unique items in a sequence by skipping duplicates."?
"Removes duplicates from sequences, preserves order." -> "Keeps only unique items in a sequence by removing duplicates; preserves order."

**Comment by Suor** [comment]
We don't need to change both. Hints in cheatsheet may be not googlable at
all.

пн, 26 мар. 2018 г., 17:57 Tal Einat <notifications@github.com>:

**Comment by taleinat** [comment]
I was referring to the doc-strings of `distinct()` and `idistinct()`.
