### ISSUE TITLE
Collection and dict utilities not working with Django QueryDict

### ISSUE THREAD

**Issue by Anon731** [Suor/funcy#74]
### Context

I have encountered situations when i use funcy.project for entities which implement dict interface and it cause some implicit errors. I am not sure if it actually funcy's bug or bug of dict interface implementation of entities i use it on.

If explanation provided in example paragraph is not enought i can later try give some exact working .py fines which reproduce such behavour (type if need).

### Example

djangorestframework ModelSerializer class (or some of it's parents) has initial_data attribute, which is `django.http.request.QueryDict`

I had following scenario trying to project it:

``` python
ipdb> pp self.initial_data
{'archived': 'false',
 'short_title': 'TT',
 'ticket_fare': '1.00',
 'ticket_type': '2',
 'title': 'test title'}

ipdb> type(self.initial_data)
<class 'django.http.request.QueryDict'>

ipdb> pp generic_relation_field_names
['history_entries']

ipdb> type(generic_relation_field_names)
<class 'list'>

ipdb> funcy.project(self.initial_data, generic_relation_field_names)
*** TypeError: expected string or bytes-like object
```

With following traceback:

```python
File ".../api/serializers/abstract.py" in _get_initial_generic_relation_fields
  104.         return funcy.project(self.initial_data, generic_relation_field_names)

File ".../.venv/lib/python3.6/site-packages/funcy/colls.py" in project
  245.     return _factory(mapping)((k, mapping[k]) for k in keys if k in mapping)

File ".../.venv/lib/python3.6/site-packages/django/http/request.py" in __init__
  407.         for key, value in limited_parse_qsl(query_string, **parse_qsl_kwargs):

File ".../.venv/lib/python3.6/site-packages/django/utils/http.py" in limited_parse_qsl
  410.         pairs = FIELDS_MATCH.split(qs, fields_limit)
```

i had similar problem with Serializer.data attribute which is `<class 'rest_framework.utils.serializer_helpers.ReturnDict'>` but i can't say if they absolutely same, because i don't have it's traceback and have not time to reproduce and provide it.

### Software:

Python==3.6.5
Django==2.1.1
djangorestframework==3.8.2
funcy==1.11

### Actual request

Either:
  - fix this behaviour
  - add assert that type of passed argument is actually dict  (wich i suppose is not a solution since it is probably break back compatibility)

**Comment by Suor** [comment]
I'll take a look.

**Comment by Suor** [comment]
The thing is Djangos `QueryDict` descends from `dict`, but breaks compatibility by changing constructor signature. So this is a bug in Django, not in funcy. All funcy collection and dict utilities won't work with it. DRFs `ReturnDict` should be fine.

A proper way to fix this is changing `QueryDict` constructor to also accept dicts and sequences of pairs as its first argument, not just string like now. This probably won't happen, but you can try opening issue or discussion on Django repo or forum.

To make this work in your case you can just cast it before projecting:
```python
project(dict(self.initial_data), generic_relation_field_names)
```

Funcy behavior at this point is correct, this is indeed a type error, but maybe surprising and not helpful. One of design rules in funcy I am following is to make it just work over being too strict. The thing is, however, to do that funcy will need to know about Django and special case it, which I don't like.

**Comment by Anon731** [comment]
I agree that such `QueryDict` implementation is not funcy's issue, but i think that is necessary to clarify when funcy can't process given structure since from given traceback I can only assume that there's either some bug in funcy either something wrong with given structure.

Since i didn't know which one and wasn't sure if that would it be useful for you to know about such behaviour i've created this issue. So my current statement is that such situation (when something of "correct type" doesn't work with some funcy's uitl for this type) can repeat and if you see some way to 
painlessly clarify such case - do it, otherwise i don't think that there's anything funcy should do with such situations and this issue can be closed.

**Comment by Suor** [comment]
Tried to make it work and failed, `QueryDict` is just fundamentally broken, not only constructor, but `.iteritems()` and even `.__getitem__()` and `.__setitem__()`. I am not up to reimplementing so much for it. So this won't work unless fixed on Djangos end.

Importing Django to just check a type is a no go, not only because this is an overkill and not funcys responsibility, but also since you can't just import Django you need to configure it first.
