### ISSUE TITLE
functions to get keys or values from a dictionary?

### ISSUE THREAD

**Issue by bijoythomas** [Suor/funcy#78]
I'm looking for functions called `keys` and `values` but cannot find anything in the docs.

**Comment by Suor** [comment]
Dicts in Python had `.keys()` and `.values()` methods.

**Comment by bijoythomas** [comment]
Ok. I was looking for functions that I could `compose` with. Any specific reason why they aren't available in `funcy`? Any opposition to adding them?

**Comment by Suor** [comment]
There is no intention to replace stdlib and methods with funcy. You can use
operator.methodcaller() to construct those

вт, 30 июл. 2019 г., 23:26 Bijoy Thomas <notifications@github.com>:
