### ISSUE TITLE
Unzip (inverted zip)

### ISSUE THREAD

**Issue by thalelinh** [Suor/funcy#80]
Maybe it's to specific, but what do you think of a function that acts like an inverse of zip, to split a list of tuples into multiple lists
izip(list) = zip(*list)

My use case was retrieving multiple values from a dict/json

`names, sizes = izip[(person['name'], person['size']) for person in people]`

**Comment by Suor** [comment]
There is this idiom of `zip(*lists)`, on which toes I don't want to step onto.
