### ISSUE TITLE
autocurry counts **kwargs against 'n' even if they do not correspond to required args

### ISSUE THREAD

**Issue by dieselmachine** [Suor/funcy#91]
I am trying to autocurry a function such as:

```
def wrap_with_tag(tag, content, **attrs):
    return '<%s%s>%s</%s>' % (tag, format_attrs(attrs), content, tag)
```

with the intent that i initial define the tag to wrap with, and then pass the function along through context processors which can add to the attributes if needed. So I'd like to be able to do:

```
link = wrap_with_tag('a', href='http://google.com')
link = link(class='external-link')
link = link('GOOGLE') # this should funally call the function and return the text
```

however, the code is counting the kwargs towards the max_n and required_n values in the autocurry function, so it calls the function prematurely and errors out due to the 'content' arg not being present. The line in question is

```if len(args) + len(kwargs) >= max_n:```

I notice that immediately following that, there is a check done against requried_n, but rather than counting all kwargs, it finds the intersection with required_names and uses that count instead:

```elif len(args) + len(set(kwargs) & required_names) >= required_n:```

Is there a particular use case i am not seeing which would fail if the intersection count was used in both places? Replacing the count in the max_n comparison with the count from the required_n comparison, my tests work perfectly and output exactly what I intend (func is only called when the 2 required args are both present).

**Comment by Suor** [comment]
I'll take a look

**Comment by Suor** [comment]
You can't use intersection of kwargs to `required_names`, you need to intersect with all names, I guess, which spec currently doesn't return. I'll need to update both `get_spec()` and `autocurry()` implementation.
