### ISSUE TITLE
map compose shortcut?

### ISSUE THREAD

**Issue by Granitosaurus** [Suor/funcy#92]
Map compose is a very useful function for processing datasets however the current implementation that I could figure out is a bit ugly:

```
from funcy import lmap, partial
data = ['one\n', ' two']

# uppercase and strip every element of a list
func = partial(lmap, compose(str.upper, str.strip))

func(data)
# ['One', 'Two']
```

Is there a way to streamline this? Ideal the syntax would be:

```
func = map_compose(str.upper, str.strip)
```

**Comment by Suor** [comment]
Thought about that. And see that I can't add all the combinations to funcy, this is where `partial()` and `compose()` should be used directly in my opinion. If you find yourself using that combination a lot you may just add this shortcut to your project utils. The difference between the lines is not big enough for me:
```python
func = partial(lmap, compose(str.upper, str.strip))
func = lmap_compose(str.upper, str.strip)
```

**Comment by Granitosaurus** [comment]
In my case this is such a common function that partial turns out looking very ugly. I did endup writing up a pretty shortcut:

```
def map_compose(*args) -> Callable:
    """returns a callable that applies compose of args to every member of an iterable"""
    return partial(lmap, rcompose(*args))
```

I still think it would be a great addition to funcy namespace for sake of convenience (e.g. open up a shell with straight import) but I guess it's easy to hack this.
