### ISSUE TITLE
Make rpartial accept keyworded arguments

### ISSUE THREAD

**Issue by ruancomelli** [Suor/funcy#95]
### Motivation

I am currently working with image processing using functions like `resize(img, shape, interpolation_method='bilinear')`, or, in a general case, `f(x, *args, **kwargs)`. Now I'm building a pipeline of functions that take a single image and output another image. So I have a lot of definitions like the following:
```
my_resizer = rpartial(resize, (128, 128), interpolation_method='nearest')
```

I could use `functools.partial`, but then I would need to use named arguments since positional arguments would start from the first argument, which is exactly the one I don't want to "freeze".
I cannot use `funcy.rpartial` directly since it does not accept keyworded arguments.

I believe that not accepting keyworded arguments is an unnecessary constraint in `funcy.rpartial`.

### Ideas

Borrowing from [functools](https://docs.python.org/3/library/functools.html#functools.partial), we could redefine `funcy.rpartial` as:
```
# idea 1
def rpartial(func, /, *args, **keywords):
    def newfunc(*fargs, **fkeywords):
        newkeywords = {**keywords, **fkeywords}
        return func(*fargs, *args, **newkeywords)
    newfunc.func = func # omit?
    newfunc.args = args # omit?
    newfunc.keywords = keywords # omit?
    return newfunc
```
Note that the only difference here is that we reverse the order of `*args, *fargs` to `*fargs, *args` in the call to `func`. This is actually what I ended up doing in my code, and I think it would be nice to have this in `funcy`.

Another point is that `functools` defines [partial objects](https://docs.python.org/3/library/functools.html#partial-objects) which have the attributes `func`, `args` and `keywords` just like in the snippet above, but the docs say that those attributes are read-only. To avoid confusion, we could just omit those attributes and redefine `rpartial` as:
```
# idea 2
def rpartial(f, *args, **kwargs):
    return lambda *a, **kw: f(*(a + args), **{**kwargs, **kw})
```

**Comment by Suor** [comment]
Makes sense. I think we should go with your second snippet. It never had introspection and nobody cared, so let's not run ahead of a train.

**Comment by Suor** [comment]
Can you make a PR?

**Comment by ruancomelli** [comment]
Sure. This will be the first PR of my life, so please tell me if I do anything stupid (but do let me try!).
